# Generated by Django 2.2.9 on 2020-01-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.URLField(max_length=512, verbose_name='원본 url 주소'),
        ),
    ]
